polling:
  name: polling_app
  version: 0.0.1
  host: 0.0.0.0
  port: 8080

postgres:
  db: polling
  user: developer
  password: 123456
  host: localhost
  port: 5432
  timezone: UTC
  sslmode: disable
  schema: public

redis:
  host: localhost
  port: 6379